package io.ssosso.common;

public enum ClassificationSmall {
  PRINCE2("PRINCE2"),
  LICENSE("자격"),
  COMP_TIA("CompTIA"),
  GENERAL("일반"),
  GO("Go"),
  READERSHIP("리더십"),
  ALIBABA_CLOUD("알리바바 클라우드"),
  IOS("iOS"),
  PRACTICAL_TECH("활용기술"),
  ORACLE("ORACLE"),
  FULL_STACK("풀스택"),
  SERVICE("서비스"),
  AUTOMATION("자동화/관리"),
  JAVA("Java"),
  TECH_REALIZATION("기술구현"),
  DATA("데이터"),
  NETWORK("네트워크"),
  MYSQL("MySQL"),
  MICROSOFT("Microsoft"),
  PROFESSIONAL_ENGINEERING("기술사"),
  FLUTTER("Flutter"),
  DEVICE("디바이스"),
  OPEN_SOURCE_DBMS("오픈소스 DBMS"),
  STRATEGY_PLANNING("전략/기획"),
  IMAGE_PROCESSING("영상처리"),
  MARKETING("마케팅"),
  MODELING("모델링"),
  PERSONAL_GENERAL_AFFAIRS("인사*총무"),
  COMMUNICATION("커뮤니케이션"),
  ENTERPRISE_PLANNING("사업기획"),
  SOLUTION_THINKING("문제해결/사고력"),
  BRAND("브랜드"),
  VIRTUALIZATION("가상화"),
  UI_UX("UI/UX"),
  MSSQL("MS SQL"),
  DESIGN_REALIZATION("설계/구현"),
  CLUSTERING("클러스터링"),
  SWIFT("Swift"),
  DATA_PROCESSING_STORE("데이터 처리/저장"),
  DESIGN("디자인"),
  CLOUD("클라우드"),
  C_SHOP("C#"),
  SYSTEM_NETWORK("시스템/네트워크"),
  PLANNING("기획"),
  R("R"),
  ELASTIC("Elastic"),
  NO_SQL("NoSQL"),
  AGILE("Agile"),
  PHP("PHP"),
  APEX("Apex"),
  DATA_ANALYSIS("데이터 분석"),
  CPE_PDU("CPE/PDU"),
  SPECIAL_LECTURE("특강"),
  EMBEDDED("임베디드"),
  MSP("MSP"),
  KOTLIN("Kotlin"),
  UNIX("Unix"),
  VR_AR("VR/AR"),
  ORDERING_MANAGEMENT("발주관리"),
  CHAT_BOT("챗봇"),
  AUDIT("감사"),
  SUPERVISION("감리"),
  HTML("HTML"),
  APPLICATION("어플리케이션"),
  DATA_STRUCTURE_ALGORITHM("자료구조/알고리즘"),
  PLATFORM("플랫폼"),
  METHODOLOGY("방법론"),
  DEVELOPMENT("개발"),
  BUILD_MANAGE("구축/운영"),
  MOCK_HACK("모의해킹"),
  ML_DL("머신러닝/딥러닝"),
  JAVASCRIPT("Javascript"),
  DOT_NET(".NET"),
  PYTHON("Python"),
  AZURE("Azure"),
  ARCHITECTURE("Architecture"),
  NEXACRO("넥사크로"),
  HYBRID("Hybrid"),
  ANALYSIS_DESIGN("분석/설계"),
  FINANCIAL_ACCOUNT_AFFAIRS("재무/회계"),
  ITIL("ITIL"),
  DOCUMENT_WRITE("문서작성"),
  SQL_TUNING("SQL/튜닝"),
  PROGRAMMING("프로그래밍"),
  ANDROID("Android"),
  RISK_MANAGEMENT("리스크관리"),
  DEV_OPS("DevOps"),
  LINUX("Linux"),
  MANAGEMENT("관리"),
  CERT_MALICIOUS_CODE("침해대응/악성코드"),
  REDHAT("RedHat"),
  DATA_AGGREGATION("데이터 수집"),
  SAP("SAP"),
  CROSS_PLATFORM("크로스 플랫폼"),
  SAS("SAS"),
  OPEN_STACK("OpenStack"),
  TEST("테스트"),
  C_CPP("C/C++"),
  SHELL("Shell"),
  OA("OA"),
  FIN_TECH("핀테크"),
  SCRUM("Scrum"),
  WEB_WAS("WEB/WAS"),
  AWS("AWS"),
  PUBLISHING("퍼블리싱"),
  SALES_FORCE("Salesforce"),
  PERFORMANCE_TUNING("성능튜닝"),
  SCALA("Scala"),
  SOLUTION("솔루션"),
  CONSULTING_LAW_AUDIT("컨설팅/법/감사"),
  DESIGN_TOOL("디자인툴"),
  PMP("PMP"),
  SW_CODING("SW코딩"),
  BUSINESS("영업"),
  MS_WINDOWS("MS Windows"),
  ;

  private String code;

  ClassificationSmall(String code) {
    this.code = code;
  }

  public String getCode() {
    return code;
  }

}
